# Generated by Django 2.1.7 on 2019-02-27 04:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='update date')),
                ('issue_type', models.CharField(choices=[('TK', 'Task'), ('ST', 'Story'), ('BG', 'Bug'), ('EP', 'Epic')], default='TK', max_length=2)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('AG', 'Assigned'), ('IP', 'Inprogress/ pending'), ('UR', 'under-review'), ('DN', 'Done'), ('CL', 'Close')], default='OP', max_length=2)),
                ('summary', models.CharField(max_length=30, null=True)),
                ('priority', models.CharField(choices=[('HGH', 'Highest'), ('HG', 'High'), ('MD', 'Medium'), ('LW', 'Low'), ('LWW', 'Lowest')], default='MD', max_length=2, null=True)),
                ('labels', models.CharField(max_length=30, null=True)),
                ('assignee', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Project.Project')),
            ],
            managers=[
                ('issue_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_sprint', to='Project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='issues',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='Issues.Sprint'),
        ),
    ]
