# Generated by Django 2.1.7 on 2019-02-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='assignee',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='issue_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='labels',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='priority',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='issues',
            name='summary',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
