# Generated by Django 2.1.7 on 2019-02-26 14:42

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='issues',
            managers=[
                ('issue_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='issues',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
