# Generated by Django 2.1.7 on 2019-02-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('Issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_labesl', to='Project.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='issues',
            name='labels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels_from_Label', to='Issues.Labels'),
        ),
    ]
