# Generated by Django 2.1.7 on 2019-02-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0002_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='Issues.Sprint'),
        ),
    ]
