# Generated by Django 2.1.7 on 2019-02-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0003_issues_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('AG', 'Assigned'), ('IP', 'Inprogress/ pending'), ('UR', 'under-review'), ('DN', 'Done'), ('CL', 'Close')], default='OP', max_length=2),
        ),
        migrations.AlterField(
            model_name='issues',
            name='sprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='Issues.Sprint'),
        ),
    ]
