# Generated by Django 2.1.7 on 2019-02-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20190225_1417'),
        ('Issues', '0003_auto_20190226_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Project'),
        ),
    ]
