# Generated by Django 2.1.7 on 2019-02-27 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0003_auto_20190227_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels_issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='labels_projects',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='issues',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Labels_projects',
        ),
        migrations.AddField(
            model_name='labels_issues',
            name='Issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_labesl_2', to='Issues.Issues'),
        ),
    ]
