# Generated by Django 2.1.7 on 2019-02-26 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Issues', '0004_issues_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='assignee',
        ),
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(choices=[('HGH', 'Highest'), ('HG', 'High'), ('MD', 'Medium'), ('LW', 'Low'), ('LWW', 'Lowest')], default='MD', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='Project.Project'),
        ),
    ]
