# Generated by Django 2.1.7 on 2019-02-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20190225_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
